package com.proeza.core.persistence.tracking.entity;

// Generated 23/08/2014 10:46:17 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import static javax.persistence.GenerationType.*;

/**
 * Movimiento generated by hbm2java
 */
@Entity
@Table(catalog = "sgs_proeza_db", name = "cmn_movimiento")
public class Movimiento implements Serializable {

	private static final long	serialVersionUID	= 1L;

	private long				id;
	private String				tipoMov;
	private long				idEntidad;
	private String				tipoEntidad;
	private Date				fechaMovimiento;
	private String				valorAnte;
	private String				valorPost;

	public Movimiento () {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId () {
		return this.id;
	}

	public void setId (long id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "f_movimiento", nullable = false, length = 10)
	public Date getFechaMovimiento () {
		return this.fechaMovimiento;
	}

	public void setFechaMovimiento (Date fechaMovimiento) {
		this.fechaMovimiento = fechaMovimiento;
	}

	@Column(name = "valor_ant", nullable = false, length = 100)
	public String getValorAnte () {
		return this.valorAnte;
	}

	public void setValorAnte (String valor) {
		this.valorAnte = valor;
	}

	@Column(name = "valor_post", nullable = false, length = 100)
	public String getValorPost () {
		return this.valorPost;
	}

	public void setValorPost (String valor) {
		this.valorPost = valor;
	}

	@Column(name = "tipo_mov", nullable = false, length = 15)
	public String getTipoMov () {
		return this.tipoMov;
	}

	public void setTipoMov (String tipo) {
		this.tipoMov = tipo;
	}

	@Column(name = "fk_entidad", nullable = false)
	public long getIdEntidad () {
		return this.idEntidad;
	}

	public void setIdEntidad (long idEntidad) {
		this.idEntidad = idEntidad;
	}

	@Column(name = "tipo_entidad", nullable = false, length = 15)
	public String getTipoEntidad () {
		return this.tipoEntidad;
	}

	public void setTipoEntidad (String tipo) {
		this.tipoEntidad = tipo;
	}
}