package proeza.mci.db;

// Generated 11/02/2013 20:32:32 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AtributosArticulo generated by hbm2java
 */
@Entity
@Table(name = "atributos_articulo", catalog = "pescalotodo", uniqueConstraints = {@UniqueConstraint(columnNames = "idAtributo"), @UniqueConstraint(columnNames = "idArticulo")})
public class AtributosArticulo implements java.io.Serializable {
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Integer           id;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "idAtributo", unique = true, nullable = false)
    private AtributoArticulo  atributo;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "idArticulo", unique = true, nullable = false)
    private ArticuloMci          articulo;

    @Column(name = "valor", nullable = false, length = 100)
    private String            valor;

    public AtributosArticulo() {
    }

    public AtributosArticulo(AtributoArticulo atributoArticulo, ArticuloMci articulo, String valor) {
        this.atributo = atributoArticulo;
        this.articulo = articulo;
        this.valor = valor;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public AtributoArticulo getAtributoArticulo() {
        return this.atributo;
    }

    public void setAtributoArticulo(AtributoArticulo atributoArticulo) {
        this.atributo = atributoArticulo;
    }

    public ArticuloMci getArticulos() {
        return this.articulo;
    }

    public void setArticulos(ArticuloMci articulo) {
        this.articulo = articulo;
    }

    public String getValor() {
        return this.valor;
    }

    public void setValor(String valor) {
        this.valor = valor;
    }
}
