package proeza.mci.db;

// Generated 21/11/2012 21:44:10 by Hibernate Tools 3.4.0.CR1

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import static javax.persistence.GenerationType.*;

/**
 * Marcas generated by hbm2java
 */
@Entity
@Table(name = "marcas", catalog = "pescalotodo")
public class MarcaMci implements java.io.Serializable, Comparable<MarcaMci> {
    private static final long serialVersionUID = 1L;

    private Integer           idMarca;
    private String            descripcion;

    public MarcaMci() {
    }

    public MarcaMci(String descripcion) {
        this.descripcion = descripcion;
    }

    public MarcaMci(String descripcion, Set<ArticuloMci> articuloses) {
        this.descripcion = descripcion;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idMarca", unique = true, nullable = false)
    public Integer getIdMarca() {
        return this.idMarca;
    }

    public void setIdMarca(Integer idMarca) {
        this.idMarca = idMarca;
    }

    @Column(name = "descripcion", nullable = false, length = 50)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + (this.getIdMarca() == null ? 0 : this.getIdMarca().hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final MarcaMci other = (MarcaMci) obj;
        if (getIdMarca() == null) {
            if (other.getIdMarca() != null)
                return false;
        } else if (!this.getIdMarca().equals(other.getIdMarca()))
            return false;
        return true;
    }

    @Override
    public String toString() {
        return this.descripcion;
    }

    @Override
    public int compareTo(MarcaMci o) {
        if (o == null)
            return -1;
        return getDescripcion().compareTo(o.getDescripcion());
    }
}
