package proeza.mci.db;

// Generated 21/11/2012 21:44:10 by Hibernate Tools 3.4.0.CR1

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import static javax.persistence.GenerationType.*;

/**
 * Tipoarticulo generated by hbm2java
 */
@Entity
@Table(name = "tipoarticulo", catalog = "pescalotodo")
public class TipoArticulo implements java.io.Serializable, Comparable<TipoArticulo> {
    private static final long serialVersionUID = 1L;

    private Integer           idTipo;
    private Categoria         categorias;
    private String            descripcion;

    public TipoArticulo() {
    }

    public TipoArticulo(String descripcion) {
        this.descripcion = descripcion;
    }

    public TipoArticulo(Categoria categorias, String descripcion, Set<ArticuloMci> articuloses) {
        this.categorias = categorias;
        this.descripcion = descripcion;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idTipo", unique = true, nullable = false)
    public Integer getIdTipo() {
        return this.idTipo;
    }

    public void setIdTipo(Integer idTipo) {
        this.idTipo = idTipo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idCategoria")
    public Categoria getCategorias() {
        return this.categorias;
    }

    public void setCategorias(Categoria categorias) {
        this.categorias = categorias;
    }

    @Column(name = "descripcion", nullable = false, length = 50)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + (getIdTipo() == null ? 0 : getIdTipo().hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TipoArticulo other = (TipoArticulo) obj;
        if (getIdTipo() == null) {
            if (other.getIdTipo() != null)
                return false;
        } else if (!getIdTipo().equals(other.getIdTipo()))
            return false;
        return true;
    }

    @Override
    public int compareTo(TipoArticulo o) {
        if (o == null)
            return -1;
        return getDescripcion().compareTo(o.getDescripcion());
    }

    @Override
    public String toString() {
        return this.descripcion;
    }
}
