package com.proeza.security.entity;

// Generated 26/08/2014 22:15:54 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import static javax.persistence.GenerationType.*;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol"
        , catalog = "seg_proeza_db")
public class Rol implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private long              id;
    private String            codigo;
    private String            nombre;
    private String            descripcion;
    private Set<UsuarioRol>   usuarios         = new HashSet<UsuarioRol>(0);

    public Rol() {
    }

    public Rol(String codigo, String nombre) {
        this.codigo = codigo;
        this.nombre = nombre;
    }

    public Rol(String codigo, String nombre, String descripcion, Set<UsuarioRol> usuarioRols) {
        this.codigo = codigo;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.usuarios = usuarioRols;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "codigo", nullable = false, length = 20)
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    @Column(name = "nombre", nullable = false, length = 45)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "descripcion", length = 100)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
    public Set<UsuarioRol> getUsuariosRol() {
        return this.usuarios;
    }

    public void setUsuariosRol(Set<UsuarioRol> usuarioRols) {
        this.usuarios = usuarioRols;
    }
}