package com.proeza.sgs.business.entity;

// Generated 23/08/2014 10:46:17 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import static javax.persistence.GenerationType.*;

/**
 * CompraArticulo generated by hbm2java
 */
@Entity
@Table(name = "compra_articulo"
, catalog = "sgs_proeza_db")
public class CompraArticulo implements java.io.Serializable {

	private static final long	serialVersionUID	= 1L;

	private long				id;
	private long				articulo;
	private long				compra;
	private int					cantidad;

	public CompraArticulo () {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId () {
		return this.id;
	}

	public void setId (long id) {
		this.id = id;
	}

	@Column(name = "fk_articulo", nullable = false)
	public long getArticulo () {
		return this.articulo;
	}

	public void setArticulo (long articulo) {
		this.articulo = articulo;
	}

	@Column(name = "fk_compra", nullable = false)
	public long getCompra () {
		return this.compra;
	}

	public void setCompra (long compra) {
		this.compra = compra;
	}

	@Column(name = "cantidad", nullable = false)
	public int getCantidad () {
		return this.cantidad;
	}

	public void setCantidad (int cantidad) {
		this.cantidad = cantidad;
	}
}