package com.proeza.sgs.business.entity;

// Generated 23/08/2014 10:46:17 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import static javax.persistence.GenerationType.*;

/**
 * MedioPago generated by hbm2java
 */
@Entity
@Table(name = "medio_pago"
		, catalog = "sgs_proeza_db")
public class MedioPago implements java.io.Serializable {

	private static final long	serialVersionUID	= 1L;

	private long		id;
	private String		codigo;
	private String		nombre;
	private String		descripcion;
	private Set<Compra>	compras	= new HashSet<Compra>(0);
	private Set<Venta>	ventas	= new HashSet<Venta>(0);

	public MedioPago() {
	}

	public MedioPago(String codigo, String nombre) {
		this.codigo = codigo;
		this.nombre = nombre;
	}

	public MedioPago(String codigo, String nombre, String descripcion, Set<Compra> compras, Set<Venta> ventas) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.compras = compras;
		this.ventas = ventas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "codigo", nullable = false, length = 10)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "nombre", nullable = false, length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medioPago")
	public Set<Compra> getCompras() {
		return this.compras;
	}

	public void setCompras(Set<Compra> compras) {
		this.compras = compras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medioPago")
	public Set<Venta> getVentas() {
		return this.ventas;
	}

	public void setVentas(Set<Venta> ventas) {
		this.ventas = ventas;
	}

}
