package com.proeza.sgs.business.entity;

// Generated 23/08/2014 10:46:17 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import static javax.persistence.GenerationType.*;

/**
 * Movimiento generated by hbm2java
 */
@Entity
@Table(catalog = "sgs_proeza_db", name = "movimiento")
public class Movimiento implements Serializable {

	private static final long	serialVersionUID	= 1L;

	private long				id;
	private Articulo			articulo;
	private TipoMovimiento		tipoMovimiento;
	private Date				fechaMovimiento;
	private String				valor;

	public Movimiento () {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId () {
		return this.id;
	}

	public void setId (long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_articulo", nullable = false)
	public Articulo getArticulo () {
		return this.articulo;
	}

	public void setArticulo (Articulo articulo) {
		this.articulo = articulo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_tipo", nullable = false)
	public TipoMovimiento getTipoMovimiento () {
		return this.tipoMovimiento;
	}

	public void setTipoMovimiento (TipoMovimiento tipoMovimiento) {
		this.tipoMovimiento = tipoMovimiento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "f_movimiento", nullable = false, length = 10)
	public Date getFechaMovimiento () {
		return this.fechaMovimiento;
	}

	public void setFechaMovimiento (Date fechaMovimiento) {
		this.fechaMovimiento = fechaMovimiento;
	}

	@Column(name = "valor", nullable = false, length = 100)
	public String getValor () {
		return this.valor;
	}

	public void setValor (String valor) {
		this.valor = valor;
	}

}
