package com.proeza.sgs.business.entity;

// Generated 23/08/2014 10:46:17 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import static javax.persistence.GenerationType.*;

/**
 * Venta generated by hbm2java
 */
@Entity
@Table(
	catalog = "sgs_proeza_db",
	name = "art_venta",
	uniqueConstraints = @UniqueConstraint(columnNames = "codigo"))
public class Venta implements Serializable {

	private static final long	serialVersionUID	= 1L;

	private long				id;
	private String				codigo;
	private MedioPago			medioPago;
	private Date				fecha;
	private double				importe;
	private Cliente				cliente;

	private Set<VentaArticulo>	articulos;

	public Venta () {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId () {
		return this.id;
	}

	public void setId (long id) {
		this.id = id;
	}

	@Column(name = "codigo", unique = true, nullable = false, length = 20)
	public String getCodigo () {
		return this.codigo;
	}

	public void setCodigo (String codigo) {
		this.codigo = codigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_medio_pago", nullable = false)
	public MedioPago getMedioPago () {
		return this.medioPago;
	}

	public void setMedioPago (MedioPago medioPago) {
		this.medioPago = medioPago;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha () {
		return this.fecha;
	}

	public void setFecha (Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "importe", nullable = false, precision = 10)
	public double getImporte () {
		return this.importe;
	}

	public void setImporte (double importe) {
		this.importe = importe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_cliente", nullable = true)
	public Cliente getCliente () {
		return this.cliente;
	}

	public void setCliente (Cliente cliente) {
		this.cliente = cliente;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "venta")
	public Set<VentaArticulo> getArticulos () {
		return this.articulos;
	}

	public void setArticulos (Set<VentaArticulo> articulos) {
		this.articulos = articulos;
	}
}