package com.proeza.sgs.business.entity;

// Generated 23/08/2014 10:46:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import static javax.persistence.GenerationType.*;

/**
 * Venta generated by hbm2java
 */
@Entity
@Table(name = "venta"
, catalog = "sgs_proeza_db")
public class Venta implements java.io.Serializable {

	private static final long	serialVersionUID	= 1L;

	private long				id;
	private MedioPago			medioPago;
	private Date				fecha;
	private double				importe;

	public Venta () {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId () {
		return this.id;
	}

	public void setId (long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_medio_pago", nullable = false)
	public MedioPago getMedioPago () {
		return this.medioPago;
	}

	public void setMedioPago (MedioPago medioPago) {
		this.medioPago = medioPago;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha () {
		return this.fecha;
	}

	public void setFecha (Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "importe", nullable = false, precision = 10)
	public double getImporte () {
		return this.importe;
	}

	public void setImporte (double importe) {
		this.importe = importe;
	}
}